title: Rebecca Li
description: > # this means to ignore newlines until "baseurl:"
  robotics enthusiast
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "htttp://rebecca.li" # the base hostname & protocol for your site, e.g. http://example.com
# Author Settings
author: Rebecca Li # add your name
author-img: og-image.jpg # add your photo
about-author: Robotics Enthusiast
# twitter: # add your Twitter handle
# facebook: # add your Facebook handle
github: rebeccali # add your Github handle
# linkedin: # add your Linkedin handle
email: rebecca@mit.edu # add your Email address

safe: false
# Disqus
discus-identifier: rebeccali # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

plugins_dir:
  - _plugins
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

gallery:
  dir: photography           # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photography"           # Title for gallery index page
  title_prefix: "Photography: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    neerja:
      best_image: large-LYC_5995.png  # The image to show on the gallery index page. Defaults to the last image.
      info:
        desc: "My friend Neerja"
    iceland:
      best_image: chair.jpg
      info:
        desc: "Iceland, 2017. Copyright Rebecca Li."
